image: registry.gitlab.com/itxtech/docker-env-cenisys

stages:
 - build
 - test
 - deploy

build:gcc:
  stage: build
  script:
   - mkdir -p build
   - cd build
   - CC=gcc CXX=g++ cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DVERSION_SUFFIX=`[ -z "$CI_BUILD_TAG" ] && echo "${CI_BUILD_REF:0:7}" || echo ""` ..
   - DESTDIR=.. ninja install
  cache:
    untracked: true
    paths:
     - build/
  artifacts:
    name: "cenisys-gcc-${CI_BUILD_REF:0:7}"
    paths:
     - usr/

build:unit-test:
  stage: build
  script:
   - mkdir -p build
   - cd build
   - CC=clang CXX=clang++ CFLAGS="-fprofile-instr-generate -fcoverage-mapping" CXXFLAGS="-fprofile-instr-generate -fcoverage-mapping" LDFLAGS="-fprofile-instr-generate" cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=../prefix/ -DBUILD_DOC=OFF -DBUILD_TEST=ON -DVERSION_SUFFIX=`[ -z "$CI_BUILD_TAG" ] && echo "${CI_BUILD_REF:0:7}" || echo ""` ..
   - ninja install
  cache:
    untracked: true
    paths:
     - build/
  dependencies: []
  artifacts:
    name: "cenisys-test-${CI_BUILD_REF:0:7}"
    paths:
     - prefix/

clang-static:
  stage: build
  script:
   - mkdir -p build
   - cd build
   - scan-build -o ../report cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOC=OFF -DBUILD_TEST=ON -DVERSION_SUFFIX=`[ -z "$CI_BUILD_TAG" ] && echo "${CI_BUILD_REF:0:7}" || echo ""` ..
   - scan-build -o ../report ninja
  dependencies: []
  artifacts:
    name: "cenisys-clang-report-${CI_BUILD_REF:0:7}"
    paths:
     - report/

test:unit-test:
  stage: test
  script:
   - LLVM_PROFILE_FILE="unit-test.profraw" LD_LIBRARY_PATH="./prefix/lib/" ./prefix/bin/cenisys-test
   - llvm-profdata merge -o unit-test.profdata unit-test.profraw
   - llvm-cov report ./prefix/lib/libCenisysCore.so -instr-profile=unit-test.profdata 
  dependencies:
     - build:unit-test
  artifacts:
    name: "cenisys-test-cov-${CI_BUILD_REF:0:7}"
    paths:
     - unit-test.profdata

pages:
  stage: deploy
  dependencies:
   - build:gcc
  script:
   - cp -r usr/share/doc/cenisys/html/ public
  artifacts:
    paths:
     - public/
  only:
   - master
